language: php
dist: trusty
sudo: false

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer update $COMPOSER_FLAGS --prefer-dist

script:
    - stty cols 120
    - php vendor/bin/phpunit
